In [95]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [96]:
df=pd.read_csv("c:/Users/tejes/Downloads/hospital_data_unclean.csv")
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,NaN,30.0,M,B-,CANCER,2024.01.31,Matthew Smith ##,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02/02/2024,Paracetamol,N
1,LEsliE tErrY,62.0,M,A+,OBESITY,2019.08.20,Samantha Davies ##,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,dAnnY SMiTH,76.0,FEMALE,A-,OBESITY,09/22/2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11/18/2020,Kevin Wells ##,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020.12.18,Ibuprofen,abn
4,ADRIeNNe bELL,43.0,FEMALE,AB+-,CANCER,2022.09.19,Kathleen Hanna ##,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10/09/2022,Penicillin,abn

In [97]:
df.isna().sum()

Name                  4440
Age                   4440
Gender                4440
Blood Type            4440
Medical Condition     4440
Date of Admission     4440
Doctor                4440
Hospital              4441
Insurance Provider    4442
Billing Amount        4440
Room Number           4441
Admission Type        4440
Discharge Date        4441
Medication            4440
Test Results          4440
dtype: int64

In [98]:
df.shape

(55505, 15)

In [99]:
df['Name']=df['Name'].str.title()

In [100]:
df.sample(5)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
21291,Paul Webster,60.0,FEMALE,B-+,ARTHRITIS,10-09-2020,Shannon Savage ##,"Inc Koch,,",Cigna,8651.334752045354 USD,296.0,Emergency,10/07/2020,Ibuprofen,abn
16856,Daniel Cohen,32.0,M,O--,CANCER,06-03-2020,Daniel Waller ##,"Alvarado-Scott,,",Cigna,6742.942082239654 USD,157.0,Elective,21-03-2020,Penicillin,abn
23231,Rebecca Austin,78.0,FEMALE,B-,NaN,NaN,Alison Bennett ##,"Adams, Bowers Escobar and,,",Aetna,49191.64768802146 USD,313.0,Emergency,04/06/2022,Paracetamol,N
27234,David Cain,71.0,FEMALE,A+,ARTHRITIS,08-04-2024,John Gill ##,"Robinson Ltd,,",UnitedHealthcare,29893.694705881528 USD,NaN,Urgent,2024.04.30,Penicillin,abn
46943,Timothy Evans,58.0,FEMALE,AB-,OBESITY,22-01-2020,Peter Navarro ##,"Howard and Lee, Harper,,",Medicare,40092.20998641654 USD,235.0,Emergency,2020.02.09,Aspirin,unknown

In [101]:
df['Gender']=df['Gender'].replace({"M":"Male","F":"Female","FEMALE":"Female"})
df.sample(5)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
10601,Keith Woods,48.0,Male,A--,CANCER,NaN,Timothy Brown ##,"Brown PLC,,",UnitedHealthcare,NaN,496.0,Elective,05/25/2023,Paracetamol,N
31022,Patricia Lowe,73.0,Female,A-+,HYPERTENSION,01-05-2020,Lisa Torres ##,"PLC Joseph,,",Cigna,24290.438712572657 USD,439.0,Elective,13-05-2020,Penicillin,N
5895,Michael Evans,NaN,Male,AB+,ASTHMA,02-01-2022,Tonya Taylor ##,"PLC Shepherd,,",Blue Cross,13073.441143500288 USD,337.0,Elective,2022.01.10,Paracetamol,N
22249,Joseph Sanchez,50.0,Female,B+-,ARTHRITIS,2020.12.19,Rhonda Callahan ##,"and Perez, Bradford Evans,,",Aetna,2942.4815979883238 USD,267.0,Emergency,12/25/2020,Lipitor,NaN
21399,Angel Moody,24.0,Female,O-+,ASTHMA,06/04/2022,James Woodard ##,"Gentry King, Moses and,,",UnitedHealthcare,40712.43322201126 USD,312.0,Emergency,19-06-2022,Paracetamol,abn

In [102]:
df['Gender'].value_counts()

Gender
Male      25605
Female    25460
Name: count, dtype: int64

In [103]:
df['Date of Admission']=df['Date of Admission'].astype(str)
df['Discharge Date']=df['Discharge Date'].astype(str)

In [104]:
df.dtypes

Name                   object
Age                   float64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount         object
Room Number           float64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [105]:
df['Date of Admission']=df['Date of Admission'].str.replace(".","-")
df['Date of Admission']=df['Date of Admission'].str.replace("/","-")
df['Discharge Date']=df['Discharge Date'].str.replace(".","-")
df['Discharge Date']=df['Discharge Date'].str.replace("/","-")

In [106]:
df[['Date of Admission','Discharge Date']].sample(5)

      Date of Admission Discharge Date
42482        11-02-2020     22-11-2020
15736        13-07-2019     2019-08-10
44424        03-28-2023     04-21-2023
9474         01-12-2021     12-06-2021
38998        18-05-2021     04-06-2021

In [107]:
df['Doctor']=df['Doctor'].str.replace("#","")

In [108]:
df['Hospital']=df['Hospital'].str.replace(",","")

In [109]:
df['Hospital'].sample(10)

8807                     Lewis PLC
36524               Wilson-Maxwell
28409    Woodard and Reese Griffin
1533                     PLC Jones
31420                    Adams-Lee
15922              Summers-Mendoza
32318              Middleton Group
11440               Vazquez-Cortez
30246       and Greene Zavala Luna
41223       and Oliver Lewis Smith
Name: Hospital, dtype: object

In [110]:
df['Insurance Provider'].unique()

array(['Blue Cross', 'Medicare', 'Aetna', nan, 'UnitedHealthcare',
       'Cigna'], dtype=object)

In [111]:
df['Insurance Provider']=df['Insurance Provider'].str.replace("H"," H")

In [112]:
df['Insurance Provider'].unique()

array(['Blue Cross', 'Medicare', 'Aetna', nan, 'United Healthcare',
       'Cigna'], dtype=object)

In [113]:
df.isna().sum()

Name                  4440
Age                   4440
Gender                4440
Blood Type            4440
Medical Condition     4440
Date of Admission        0
Doctor                4440
Hospital              4441
Insurance Provider    4442
Billing Amount        4440
Room Number           4441
Admission Type        4440
Discharge Date           0
Medication            4440
Test Results          4440
dtype: int64

In [114]:
df['Name']=df['Name'].fillna("Unknown")

In [115]:
df['Name'].isna().sum()

np.int64(0)

In [116]:
df['Age']=df['Age'].fillna(df['Age'].mean().round(2))

In [117]:
df['Age'].isna().sum()

np.int64(0)

In [118]:
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])

In [119]:
df['Gender'].isna().sum()

np.int64(0)

In [120]:
df['Gender'].value_counts()

Gender
Male      30045
Female    25460
Name: count, dtype: int64

In [121]:
df['Blood Type']=df['Blood Type'].fillna(df['Blood Type'].mode()[0])

In [122]:
df['Blood Type'].isna().sum()

np.int64(0)

In [123]:
df['Blood Type'].value_counts()

Blood Type
A-      6110
O+      1650
B-      1644
O-      1639
A+      1637
AB-     1627
B-+     1620
AB+-    1619
A+-     1618
AB-+    1618
B+-     1613
AB+     1613
B-      1605
A-      1603
B+      1597
B++     1588
A--     1586
AB++    1582
B+      1582
O++     1579
A+      1576
A++     1572
AB+     1571
A-+     1569
B--     1569
AB-     1567
AB--    1565
O--     1565
O+-     1562
O+      1557
O-+     1556
O-      1546
Name: count, dtype: int64

In [124]:
df.sample(10)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
20618,Luis Wright,85.0,Male,A+-,DIABETES,04-03-2024,Cody White,Group Adams,Cigna,NaN,193.0,Elective,2024-04-11,Ibuprofen,N
2779,Jason Patterson,80.0,Male,O-,HYPERTENSION,2022-05-11,Claudia Martinez,and Butler King Morton,Cigna,26395.43786896715 USD,304.0,Emergency,05-16-2022,Ibuprofen,unknown
45958,Sarah Marshall,42.0,Male,O-,DIABETES,12-01-2020,Melissa Becker,Taylor Ltd,Blue Cross,7146.812625468181 USD,389.0,Emergency,13-12-2020,Penicillin,unknown
27532,Mr. Paul Ruiz,30.0,Male,AB+,DIABETES,31-12-2021,NaN,Mcintyre Finley and Jones,Cigna,30245.5110491449 USD,264.0,Urgent,01-01-2022,Penicillin,abn
15335,Abigail Sims,61.0,Male,A+,DIABETES,07-08-2022,NaN,LLC Montoya,Aetna,29032.89532783074 USD,268.0,Urgent,07-22-2022,NaN,unknown
41912,Christopher Vega,36.0,Male,B-,OBESITY,07-15-2021,Cynthia Johnson,Gardner-Snyder,Blue Cross,10707.378850439234 USD,117.0,Elective,30-07-2021,Penicillin,N
35776,Unknown,46.0,Female,AB++,HYPERTENSION,06-07-2022,Adam Smith,and Taylor Murillo Estrada,Medicare,38126.71026839612 USD,264.0,Urgent,06-11-2022,Ibuprofen,abn
46489,Meagan Flynn,43.0,Female,A+,ARTHRITIS,18-01-2022,Justin Gonzalez,Short LLC,Aetna,2247.375358787909 USD,275.0,Urgent,03-02-2022,Paracetamol,unknown
3490,James Curry,65.0,Female,A-,OBESITY,17-10-2022,NaN,NaN,Cigna,21914.03177865377 USD,232.0,Emergency,11-09-2022,Ibuprofen,NaN
25788,Brandy Reynolds,51.0,Female,A++,NaN,10-14-2019,Jennifer Clark,Hodge-Love,NaN,7287.773893038525 USD,172.0,Elective,nan,Ibuprofen,abn

In [125]:
df['Doctor'].value_counts()

Doctor
Michael Smith        24
John Smith           21
Michael Johnson      20
Robert Smith         19
James Smith          18
                     ..
Brady Burke           1
Laura Robinson        1
Kristen King          1
Nicholas Schmidt      1
Bernard Ruiz          1
Name: count, Length: 37819, dtype: int64

In [126]:
df['Doctor'].isna().sum()

np.int64(4440)

In [127]:
df['Doctor']=df['Doctor'].fillna("Unknown")

In [128]:
df['Doctor'].isna().sum()

np.int64(0)

In [129]:
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [130]:
df['Medical Condition']=df['Medical Condition'].fillna("Unknown")

In [131]:
df['Medical Condition'].isna().sum()

np.int64(0)

In [132]:
df['Hospital'].value_counts()

Hospital
LLC Smith                     38
Ltd Smith                     36
Smith Ltd                     36
Smith Group                   34
Smith Inc                     33
                              ..
Sullivan-Miller                1
Velasquez-Gates                1
Simmons Murray and Raymond     1
and Cabrera Kim Mills          1
Group Middleton                1
Name: count, Length: 37356, dtype: int64

In [133]:
df['Hospital']=df['Hospital'].fillna("Unknown")

In [134]:
df['Hospital'].value_counts()

Hospital
Unknown                       4441
LLC Smith                       38
Smith Ltd                       36
Ltd Smith                       36
Smith Group                     34
                              ...
and Moreno Crosby Young          1
Khan-Snow                        1
and Wilson Hampton Roberts       1
and Gray Fleming Young           1
Anderson-Wright                  1
Name: count, Length: 37357, dtype: int64

In [135]:
df['Insurance Provider']=df['Insurance Provider'].fillna("Unknown")

In [136]:
df.head(10)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Unknown,30.00,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.00,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.00,Female,A-,OBESITY,09-22-2022,Unknown,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,Unknown,28.00,Female,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.00,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
5,Unknown,36.00,Male,A+,ASTHMA,2023-12-20,Taylor Newton,Nunez-Humphrey,United Healthcare,48145.11095104189 USD,389.0,Urgent,2023-12-24,Ibuprofen,N
6,Edward Edwards,21.00,Female,AB-,DIABETES,11-03-2020,Kelly Olson,Group Middleton,Medicare,19580.87234486093 USD,389.0,Emergency,15-11-2020,Paracetamol,unknown
7,Christina Martinez,51.58,Male,A++,Unknown,2021-12-28,Suzanne Thomas,Powell Robinson and Valdez,Cigna,45820.46272159459 USD,277.0,NaN,01-07-2022,NaN,unknown
8,Jasmine Aguilar,82.00,Male,AB+-,Unknown,01-07-2020,Daniel Ferguson,Sons Rich and,Cigna,50119.222791548505 USD,316.0,Elective,07-14-2020,Aspirin,abn
9,Christopher Berg,58.00,Female,AB-+,CANCER,2021-05-23,Heather Day,Unknown,United Healthcare,NaN,249.0,Elective,22-06-2021,Paracetamol,unknown

In [137]:
df['Billing Amount']=df['Billing Amount'].astype(str)
df['Billing Amount']=df['Billing Amount'].str.replace(" USD","")

In [138]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,Female,A-,OBESITY,09-22-2022,Unknown,Cook PLC,Aetna,27955.096078842456,205.0,Emergency,07-10-2022,Aspirin,N
3,Unknown,28.0,Female,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,Female,AB+-,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317813937623,458.0,Urgent,10-09-2022,Penicillin,abn

In [139]:
df['Billing Amount']=df['Billing Amount'].astype(float).round(2)
df.sample(10)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
20660,Unknown,69.00,Male,AB+,HYPERTENSION,05-09-2019,Carl Johnson,and Chambers Ball Taylor,Medicare,2331.92,280.0,Elective,06-07-2019,Lipitor,unknown
51913,Justin Beck,72.00,Female,A-,ARTHRITIS,2023-10-24,David Wilson,Matthews-Romero,Cigna,41566.37,308.0,Urgent,11-14-2023,Penicillin,abn
36010,Mr. Christopher Cuevas,51.58,Female,A-,ASTHMA,12-03-2019,Francisco Webb,Inc Jackson,Unknown,3182.71,150.0,Elective,01-01-2020,Penicillin,abn
8883,Brian Greene,22.00,Male,B+,DIABETES,2019-06-07,Thomas Morton,Allen-Foster,United Healthcare,NaN,277.0,Elective,06-11-2019,Lipitor,abn
29268,Kimberly Daniels,65.00,Female,O-,DIABETES,2023-12-28,Jennifer Reynolds,Group Johnson,United Healthcare,1949.87,317.0,Urgent,24-01-2024,Penicillin,unknown
52980,Lauren Goodman,51.58,Female,B-+,ASTHMA,03-11-2019,Mindy Wilson,Kelly Ltd,Cigna,44637.32,294.0,Urgent,11-05-2019,Penicillin,NaN
2142,Charles Gonzalez,42.00,Female,O+,Unknown,06-04-2024,Olivia Hill,Reed-Guzman,Cigna,43317.62,408.0,Elective,2024-04-24,Aspirin,N
27105,Robert Henry,27.00,Male,A+,ASTHMA,12-08-2020,Peter Cole,Webb Lee Hendricks and,Medicare,14413.84,314.0,Urgent,01-06-2021,Lipitor,N
9151,Robert Smith,60.00,Female,A-,OBESITY,24-04-2021,Jason Lee,Vega-Walker,Unknown,23143.42,255.0,Elective,05-08-2021,Lipitor,N
8805,Elizabeth Spears,82.00,Female,A-,CANCER,nan,Patricia Rivas,Unknown,Cigna,4566.56,274.0,Urgent,nan,Penicillin,abn

In [140]:
df['Billing Amount'].isna().sum()

np.int64(4440)

In [141]:
df['Billing Amount']=df['Billing Amount'].fillna(df['Billing Amount'].mean())
df['Billing Amount'].isna().sum()

np.int64(0)

In [142]:
df['Test Results'].isna().sum()

np.int64(4440)

In [143]:
df['Test Results']=df['Test Results'].fillna("Unknown")
df['Test Results']=df['Test Results'].str.replace("abn","Abnormal")
df['Test Results']=df['Test Results'].str.replace("N","Normal")

In [144]:
df['Test Results'].isna().sum()

np.int64(0)

In [145]:
df['Test Results'].value_counts()

Test Results
Abnormal    17123
Normal      17039
unknown     16903
Unknown      4440
Name: count, dtype: int64

In [146]:
df['Test Results']=df['Test Results'].str.replace("Unknown","unknown")

In [147]:
df['Test Results'].value_counts()

Test Results
unknown     21343
Abnormal    17123
Normal      17039
Name: count, dtype: int64

In [148]:
df.isna().sum()

Name                     0
Age                      0
Gender                   0
Blood Type               0
Medical Condition        0
Date of Admission        0
Doctor                   0
Hospital                 0
Insurance Provider       0
Billing Amount           0
Room Number           4441
Admission Type        4440
Discharge Date           0
Medication            4440
Test Results             0
dtype: int64

In [149]:
df['Medication']=df['Medication'].fillna("Unknown")

In [150]:
df['Room Number']=df['Room Number'].fillna("Not Assigned")

In [151]:
df['Admission Type'].value_counts()

Admission Type
Elective     17189
Urgent       17056
Emergency    16820
Name: count, dtype: int64

In [152]:
df['Admission Type'].isna().sum()

np.int64(4440)

In [153]:
df['Admission Type']=df['Admission Type'].fillna("Unknown")

In [154]:
df.isna().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [155]:
df.dtypes

Name                   object
Age                   float64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number            object
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [156]:
df['Date of Admission']=df['Date of Admission'].str.strip()
df['Discharge Date']=df['Discharge Date'].str.strip()

In [157]:
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'], format='mixed', errors='coerce')
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'], format='mixed', errors='coerce')

In [158]:
df.dtypes

Name                          object
Age                          float64
Gender                        object
Blood Type                    object
Medical Condition             object
Date of Admission     datetime64[ns]
Doctor                        object
Hospital                      object
Insurance Provider            object
Billing Amount               float64
Room Number                   object
Admission Type                object
Discharge Date        datetime64[ns]
Medication                    object
Test Results                  object
dtype: object

In [159]:
df.sample(10)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
41751,Kevin Clarke,73.0,Male,B+,HYPERTENSION,2022-12-18,Maria Whitney,Oconnor-Ross,Cigna,107.330000,313.0,Elective,2023-01-10,Penicillin,Normal
30397,Jesse Thomas,61.0,Female,B++,ASTHMA,2023-01-10,Steven Hubbard,Alexander Wagner and Hill,United Healthcare,13919.860000,207.0,Elective,2023-01-21,Lipitor,Abnormal
18256,Jordan Acosta,26.0,Female,O++,HYPERTENSION,2023-04-07,David Garcia,Prince and Tucker Dyer,Cigna,37712.080000,493.0,Elective,2023-07-05,Penicillin,Abnormal
51022,John Williams,42.0,Male,B-,ASTHMA,2023-12-28,Unknown,Ltd Smith,Cigna,6509.400000,Not Assigned,Elective,2024-01-02,Unknown,Normal
9902,Vicki Smith,19.0,Male,A++,DIABETES,2021-12-28,Shane Brown,Group Mills,Cigna,30281.640000,333.0,Elective,2022-01-21,Paracetamol,unknown
30540,Mikayla Wiley,19.0,Female,A++,HYPERTENSION,2021-09-02,Unknown,and Bowman Ward Meyer,Medicare,13692.230000,222.0,Urgent,2021-09-06,Lipitor,Normal
4912,Jamie Thomas,34.0,Male,AB+-,HYPERTENSION,NaT,Rhonda Moore,Waters-Chapman,Medicare,25553.788182,226.0,Urgent,2023-04-21,Penicillin,Normal
21459,Robert Frost,62.0,Male,B+,HYPERTENSION,2020-11-03,Dr. Jacob Liu,Unknown,Medicare,17118.620000,224.0,Elective,2020-11-18,Ibuprofen,Normal
23664,Lisa Griffin,78.0,Male,B-+,HYPERTENSION,2019-07-23,Stephanie Hartman,Unknown,United Healthcare,7921.160000,290.0,Urgent,2019-07-25,Lipitor,Normal
17914,Cynthia Luna,77.0,Female,AB-,Unknown,2022-12-25,Randy Wilson,Booth Group,Cigna,42721.580000,403.0,Unknown,2023-01-23,Penicillin,Abnormal

In [160]:
df['Date of Admission'] = df['Date of Admission'].dt.strftime('%d/%m/%Y')
df['Discharge Date'] = df['Discharge Date'].dt.strftime('%d/%m/%Y')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Unknown,30.0,Male,B-,CANCER,31/01/2024,Matthew Smith,Sons and Miller,Blue Cross,18856.28,328.0,Urgent,02/02/2024,Paracetamol,Normal
1,Leslie Terry,62.0,Male,A+,OBESITY,20/08/2019,Samantha Davies,Kim Inc,Medicare,33643.33,265.0,Emergency,26/08/2019,Ibuprofen,unknown
2,Danny Smith,76.0,Female,A-,OBESITY,22/09/2022,Unknown,Cook PLC,Aetna,27955.10,205.0,Emergency,10/07/2022,Aspirin,Normal
3,Unknown,28.0,Female,O+,DIABETES,18/11/2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78,450.0,Elective,18/12/2020,Ibuprofen,Abnormal
4,Adrienne Bell,43.0,Female,AB+-,CANCER,19/09/2022,Kathleen Hanna,Unknown,Unknown,14238.32,458.0,Urgent,09/10/2022,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,21/02/2022,Cassandra Montoya,Walls-Castillo,Unknown,19601.38,420.0,Emergency,03/09/2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23/10/2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.62,357.0,Urgent,20/11/2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20/12/2019,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.98,136.0,Elective,05/01/2020,Aspirin,Abnormal
55503,Aaron Craig,22.0,Female,O-+,ARTHRITIS,21/03/2024,Justin Wolfe,Unknown,Medicare,13007.89,448.0,Elective,19/04/2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,Female,B+,HYPERTENSION,18/07/2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.15,Not Assigned,Emergency,NaN,Penicillin,Normal

In [161]:
df.isna().sum()

Name                     0
Age                      0
Gender                   0
Blood Type               0
Medical Condition        0
Date of Admission     4440
Doctor                   0
Hospital                 0
Insurance Provider       0
Billing Amount           0
Room Number              0
Admission Type           0
Discharge Date        4441
Medication               0
Test Results             0
dtype: int64

In [162]:
df['Date of Admission']=df['Date of Admission'].fillna("Unknown")
df['Discharge Date']=df['Discharge Date'].fillna("Unknown")

In [163]:
df['Blood dup']=df['Blood Type'].str.strip()

In [164]:
df['Blood dup'].unique()

array(['B-', 'A+', 'A-', 'O+', 'AB+-', 'AB-', 'A++', 'AB-+', 'A-+', 'A+-',
       'A--', 'B+', 'AB+', 'O-+', 'O--', 'B+-', 'B--', 'AB++', 'B-+',
       'O++', 'O+-', 'B++', 'AB--', 'O-'], dtype=object)

In [165]:
df['Blood dup']=df['Blood dup'].str[:3]
df['Blood dup'].unique()

array(['B-', 'A+', 'A-', 'O+', 'AB+', 'AB-', 'A++', 'A-+', 'A+-', 'A--',
       'B+', 'O-+', 'O--', 'B+-', 'B--', 'B-+', 'O++', 'O+-', 'B++', 'O-'],
      dtype=object)

In [166]:
df['Blood dup']=df['Blood dup'].str.replace("++","+")
df['Blood dup']=df['Blood dup'].str.replace("--","-")
df['Blood dup']=df['Blood dup'].str.replace("+-","+")
df['Blood dup']=df['Blood dup'].str.replace("-+","-")
df[['Blood Type','Blood dup']].sample(10)

      Blood Type Blood dup
3460        AB-        AB-
5020          O+        O+
32218        O++        O+
14481        O+         O+
44214         O-        O-
54797        B-+        B-
46852        O++        O+
43078         O+        O+
2572          B+        B+
38129        O-+        O-

In [167]:
df['Blood dup'].unique()

array(['B-', 'A+', 'A-', 'O+', 'AB+', 'AB-', 'B+', 'O-'], dtype=object)

In [168]:
df.sample(5)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Blood dup
2811,Allison Bowers,81.00,Female,B-,OBESITY,29/03/2024,Tony Ross,Carson-Johnson,Blue Cross,13351.43,448.0,Urgent,04/12/2024,Aspirin,unknown,B-
33930,Mr. Michael Smith,51.58,Female,O-+,Unknown,29/01/2024,Annette Smith,Bean and Morrow Ingram,Medicare,8589.48,478.0,Elective,27/02/2024,Ibuprofen,Normal,O-
30198,Ashley Thomas,43.00,Female,A-,OBESITY,28/09/2019,Jason Morales,Good-Martin,Blue Cross,12506.80,Not Assigned,Urgent,Unknown,Lipitor,Abnormal,A-
9564,Matthew Mendez,42.00,Female,O++,ASTHMA,11/12/2023,Courtney Reed,Valenzuela-Robinson,United Healthcare,50046.75,371.0,Elective,31/12/2023,Paracetamol,Normal,O+
28988,Kevin Thompson,63.00,Male,A--,CANCER,26/12/2019,Taylor Perry,Nelson Hall and Williams,Medicare,31856.74,476.0,Emergency,20/01/2020,Ibuprofen,Abnormal,A-

In [169]:
df.drop('Blood Type',axis=1,inplace=True)

In [170]:
df.rename(columns={'Blood dup':'Blood Type'},inplace=True)

In [171]:
df.columns

Index(['Name', 'Age', 'Gender', 'Medical Condition', 'Date of Admission',
       'Doctor', 'Hospital', 'Insurance Provider', 'Billing Amount',
       'Room Number', 'Admission Type', 'Discharge Date', 'Medication',
       'Test Results', 'Blood Type'],
      dtype='object')

In [172]:
df.isna().sum()

Name                  0
Age                   0
Gender                0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
Blood Type            0
dtype: int64

In [173]:
df.dtypes

Name                   object
Age                   float64
Gender                 object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number            object
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
Blood Type             object
dtype: object

In [174]:
df['Date of Admission']=pd.to_datetime(df['Date of Admission'],format='%d/%m/%Y',errors='coerce')
df['Discharge Date']=pd.to_datetime(df['Discharge Date'],format='%d/%m/%Y',errors='coerce')
df.dtypes

Name                          object
Age                          float64
Gender                        object
Medical Condition             object
Date of Admission     datetime64[ns]
Doctor                        object
Hospital                      object
Insurance Provider            object
Billing Amount               float64
Room Number                   object
Admission Type                object
Discharge Date        datetime64[ns]
Medication                    object
Test Results                  object
Blood Type                    object
dtype: object

In [175]:
df.sample(5)

,Name,Age,Gender,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Blood Type
48751,Nathan Greer,35.0,Male,DIABETES,2019-11-23,Joshua Velasquez,Giles Ltd,United Healthcare,40212.40,447.0,Emergency,2019-12-16,Aspirin,Normal,A-
26068,Kathryn Sawyer,26.0,Female,CANCER,NaT,Alicia Friedman,and Luna Castro Stevens,Medicare,2770.90,Not Assigned,Emergency,2022-01-13,Ibuprofen,unknown,O+
23872,Mrs. Caitlin Daniel Md,46.0,Male,HYPERTENSION,NaT,Elizabeth Wilson,Newman LLC,Medicare,35566.98,438.0,Emergency,2023-03-09,Paracetamol,unknown,B-
6435,Heather Morris,67.0,Female,ARTHRITIS,2023-01-19,Unknown,Ross Group,Cigna,16788.81,125.0,Emergency,2023-02-02,Ibuprofen,Abnormal,AB+
47774,Noah Richards,75.0,Male,Unknown,2019-06-19,William Stout,Fox-Brennan,United Healthcare,41700.45,326.0,Elective,2019-06-29,Paracetamol,Normal,A-

In [176]:
df.duplicated().sum()

np.int64(55)

In [177]:
df.drop_duplicates(inplace=True)

In [178]:
df.isna().sum()

Name                     0
Age                      0
Gender                   0
Medical Condition        0
Date of Admission     4440
Doctor                   0
Hospital                 0
Insurance Provider       0
Billing Amount           0
Room Number              0
Admission Type           0
Discharge Date        4440
Medication               0
Test Results             0
Blood Type               0
dtype: int64

In [179]:
df['Date of Admission']=df['Date of Admission'].fillna("Unknown")
df['Discharge Date']=df['Discharge Date'].fillna("Unknown")

In [180]:
df.isna().sum()

Name                  0
Age                   0
Gender                0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
Blood Type            0
dtype: int64

In [181]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
Blood Type            0
dtype: int64

In [182]:
df.to_csv("c:/Users/tejes/Downloads/hospital_data_cleaned.csv",index=False)